name: Test
on: [push]
jobs:

  test:
    name: Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.18', '1.19', '1.20', '1.21', '1.22', '1.23', '1.24']

    steps:
    - name: "Set up Go ${{ matrix.go_version }}"
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run tests
      run: go test -v -race

    - name: Notify
      uses: dirty-go/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.TELEGRAM_CHAT }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        status: ${{ job.status }}

